Added README.md
Zarebin/nextgen-js-4 pull request #8
Opened 2022-09-03 08:52 UTC by nazaninsnr

2022-09-04 08:42 UTC, ketabi requested changes

2022-09-04 08:42 UTC, ketabi commented on intelligent-response/Naghavi/dist/index.html
> +<!DOCTYPE html>
You have to put this file (dist folder totally ) in .gitignore

2022-09-06 05:38 UTC, garshasbi-f commented on intelligent-response/Naghavi/.gitignore
> +node_modules
You must also put the dist file in the gitignore

2022-09-07 06:49 UTC, garshasbi-f requested changes

2022-09-07 06:49 UTC, garshasbi-f commented on intelligent-response/Naghavi/src/placeMark.js
> +  <style>
You could bring the codes related to the style of this component in a separate css file and import it in this js file.

2023-11-14 12:19 UTC, closed without merging